//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.13 at 08:02:12 AM SAST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.github.com/bruce_mig/spring_boot_soap_ws/loan_ligibility", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.github.bruce_mig.spring_boot_soap_ws.loan_eligibility;
